version: '3.8'

services:
  app:
    build: .
    container_name: escrow-agent-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./:/app
      - /app/node_modules


  db:
    image: postgres:13
    container_name: escrow-agent-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: ./frontend
    container_name: escrow-agent-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080/api
      - NEXT_PUBLIC_BASE_URL=http://localhost:8080
    volumes:
    - ./frontend:/app
    - /app/node_modules
volumes:
  postgres_data:
