// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"net/http"
)

// Injectors from wire.go:

func InitializeApp() (*http.Server, func(), error) {
	router := InitializeRouter()
	handler := InitializeCORSHandler(router)
	server := InitializeServer(handler)
	return server, func() {
	}, nil
}
