openapi: 3.0.0
info:
  title: Escrow Agent API
  description: API for managing escrow transactions.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /login:
    post:
      summary: Logs in a user
      description: Authenticates a user and returns a JWT token.
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid username or password

  /signup:
    post:
      summary: Signs up a new user
      description: Registers a new user and returns success status.
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: Successful signup
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        '400':
          description: Invalid signup data

  /api/escrow:
    post:
      summary: Creates a new escrow
      description: Creates an escrow transaction between a buyer and seller.
      tags:
        - escrow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEscrowRequest'
      responses:
        '201':
          description: Escrow created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateEscrowResponse'
        '400':
          description: Invalid escrow data
      security:
        - BearerAuth: []  

  /api/escrow/{id}/release:
      post:
        summary: Releases escrow funds
        description: Releases funds from escrow to the seller.
        tags:
          - escrow
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
            description: "Escrow ID of the transaction"
        responses:
          '200':
            description: Funds released successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ReleaseFundsResponse'
          '400':
            description: Invalid escrow ID or escrow not in pending state
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
        security:
          - BearerAuth: [] 

  /api/escrow/{id}/dispute:
    post:
      summary: Disputes an escrow transaction
      description: Files a dispute for an escrow transaction.
      tags:
        - escrow
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "Escrow ID of the transaction"
      responses:
        '200':
          description: Dispute filed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisputeEscrowResponse'
        '400':
          description: Invalid escrow ID or escrow not in pending state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'   
      security:
        - BearerAuth: []

  /api/escrow/pending:
    get:
      summary: Gets all pending escrows
      description: Returns a list of all pending escrow transactions.
      tags:
        - escrow
      responses:
        '200':
          description: List of pending escrows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PendingEscrowResponse'
        '500':
          description: Internal server error
      security:
        - BearerAuth: []

  /api/escrow/disputed:
    get:
      summary: Gets all disputed escrows
      description: Returns a list of all disputed escrow transactions.
      tags:
        - escrow
      responses:
        '200':
          description: List of disputed escrows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DisputedEscrowResponse'
        '500':
          description: Internal server error
      security:
        - BearerAuth: []

  /api/upload:
    post:
      summary: Uploads a file
      description: Uploads a file for escrow documents.
      tags:
        - fileupload (TODO feature)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadRequest'
      responses:
        '200':
          description: File uploaded successfully
      security:
        - BearerAuth: []

  /api/customer:
    post:
      summary: Creates a new customer
      description: Adds a new customer to the escrow system.
      tags:
        - customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
      responses:
        '201':
          description: Customer created successfully
        '400':
          description: Invalid customer data
      security:
        - BearerAuth: []

components:

  securitySchemes:
    BearerAuth:  
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    LoginResponse:
      type: object
      properties:
        token:
          type: string

    SignupRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

      required:
        - username
        - password
    SignupResponse:
      type: object
      properties:
        message:
          type: string
          example: "User created successfully"

    CreateEscrowRequest:
      type: object
      properties:
        buyer_id:
          type: string
          description: "ID of the buyer"
        seller_id:
          type: string
          description: "ID of the seller"
        amount:
          type: number
          format: float
          description: "Amount for the escrow"
        description:
          type: string
          description: "Description of the escrow transaction"
      required:
        - buyer_id
        - seller_id
        - amount
        - description

    CreateEscrowResponse:
      type: object
      properties:
        escrow_id:
          type: string
          description: "The ID of the newly created escrow transaction"
        status:
          type: string
          description: "The current status of the escrow"
        created_at:
          type: string
          format: date-time
          description: "The creation time of the escrow"

    PendingEscrowResponse:
      type: object
      properties:
        escrow_id:
          type: string
          description: "The ID of the escrow transaction"
        buyer_id:
          type: string
          description: "The ID of the buyer"
        seller_id:
          type: string
          description: "The ID of the seller"
        amount:
          type: number
          description: "The amount of the escrow transaction"
        status:
          type: string
          description: "The current status of the escrow"
        created_at:
          type: string
          format: date-time
          description: "The creation time of the escrow"
        description:
          type: string
          description: "Description of the escrow transaction"

    DisputedEscrowResponse:
      type: object
      properties:
        escrow_id:
          type: string
          description: "The ID of the disputed escrow transaction"
        buyer_id:
          type: string
          description: "The ID of the buyer"
        seller_id:
          type: string
          description: "The ID of the seller"
        amount:
          type: number
          description: "The amount of the escrow transaction"
        status:
          type: string
          description: "The current status of the escrow, which is 'disputed'"
        created_at:
          type: string
          format: date-time
          description: "The creation time of the escrow"
        description:
          type: string
          description: "Description of the escrow transaction"

    ReleaseFundsResponse:
      type: object
      properties:
        message:
          type: string
          example: "Funds released successfully"
        escrow_id:
          type: string
          description: "The ID of the escrow that was released"
        status:
          type: string
          example: "released"
          description: "The new status of the escrow after releasing the funds"
        released_at:
          type: string
          format: date-time
          description: "The timestamp of when the funds were released"

    DisputeEscrowResponse:
      type: object
      properties:
        message:
          type: string
          example: "Dispute filed successfully"
        escrow_id:
          type: string
          description: "The ID of the escrow that was disputed"
        status:
          type: string
          example: "disputed"
          description: "The new status of the escrow after the dispute"
        disputed_at:
          type: string
          format: date-time
          description: "The timestamp of when the dispute was filed"
          
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Invalid escrow ID or escrow not in pending state"

    UploadRequest:
      type: object
      properties:
        file:
          type: string
          format: binary

    CreateCustomerRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
      required:
        - name
        - email
        - phone
