openapi: 3.0.0
info:
  title: Escrow Agent API
  description: API for managing escrow transactions.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /login:
    post:
      summary: Logs in a user
      description: Authenticates a user and returns a JWT token.
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid username or password

  /register:
    post:
      summary: Registers a new user
      description: Registers a new user and returns success status.
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Successful signup
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Invalid signup data

  /api/profile:
    get:
      summary: Get the logged-in user's profile
      description: Returns the profile information of the authenticated user.
      tags:
        - profile
      responses:
        '200':
          description: Profile information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '404':
          description: User not found
        '500':
          description: Server error
      security:
        - BearerAuth: []

    put:
      summary: Update the logged-in user's profile
      description: Allows the authenticated user to update their profile information (username, password, and role).
      tags:
        - profile
      requestBody:
        description: Fields to update in the user's profile (only the fields that need updating should be included)
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: New username
                  example: new_username
                password:
                  type: string
                  description: New password (will be securely hashed before storing)
                  example: new_password
                role:
                  type: string
                  description: The user's new role (admin, buyer, or seller)
                  example: admin
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Profile updated successfully
        '400':
          description: Bad request - Invalid input data
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '500':
          description: Internal server error
      security:
        - BearerAuth: []

  /api/transactions:
    post:
      summary: Create a new transaction (by buyer)
      description: Allows a buyer to create a new transaction by specifying the seller, amount, and status.
      tags:
        - transactions
      requestBody:
        description: Information required to create a new transaction
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                seller_id:
                  type: integer
                  description: The ID of the seller
                  example: 2
                amount:
                  type: number
                  format: float
                  description: The transaction amount
                  example: 500.00
                status:
                  type: string
                  description: The status of the transactio, defaults to pending
                  example: pending
      responses:
        '201':
          description: Transaction created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request (missing or invalid input data)
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '500':
          description: Internal server error
      security:
        - BearerAuth: []

  /api/escrow:
    post:
      summary: Creates a new escrow
      description: Creates an escrow transaction between a buyer and seller.
      tags:
        - escrow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEscrowRequest'
      responses:
        '201':
          description: Escrow created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateEscrowResponse'
        '400':
          description: Invalid escrow data
      security:
        - BearerAuth: []  

  /api/escrow/{id}/release:
      post:
        summary: Releases escrow funds
        description: Releases funds from escrow to the seller.
        tags:
          - escrow
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
            description: "Escrow ID of the transaction"
        responses:
          '200':
            description: Funds released successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ReleaseFundsResponse'
          '400':
            description: Invalid escrow ID or escrow not in pending state
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
        security:
          - BearerAuth: [] 

  /api/escrow/{id}/dispute:
    post:
      summary: Disputes an escrow transaction
      description: Files a dispute for an escrow transaction.
      tags:
        - escrow
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "Escrow ID of the transaction"
      responses:
        '200':
          description: Dispute filed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisputeEscrowResponse'
        '400':
          description: Invalid escrow ID or escrow not in pending state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'   
      security:
        - BearerAuth: []

  /api/escrow/pending:
    get:
      summary: Gets all pending escrows
      description: Returns a list of all pending escrow transactions.
      tags:
        - escrow
      responses:
        '200':
          description: List of pending escrows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PendingEscrowResponse'
        '500':
          description: Internal server error
      security:
        - BearerAuth: []

  /api/escrow/disputed:
    get:
      summary: Gets all disputed escrows
      description: Returns a list of all disputed escrow transactions.
      tags:
        - escrow
      responses:
        '200':
          description: List of disputed escrows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DisputedEscrowResponse'
        '500':
          description: Internal server error
      security:
        - BearerAuth: []

  /api/upload:
    post:
      summary: Uploads a file
      description: Uploads a file for escrow documents.
      tags:
        - fileupload (TODO feature)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadRequest'
      responses:
        '200':
          description: File uploaded successfully
      security:
        - BearerAuth: []

  /api/customer:
    post:
      summary: Creates a new customer
      description: Adds a new customer to the escrow system.
      tags:
        - customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
      responses:
        '201':
          description: Customer created successfully
        '400':
          description: Invalid customer data
      security:
        - BearerAuth: []

components:

  securitySchemes:
    BearerAuth:  
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    LoginResponse:
      type: object
      properties:
        token:
          type: string

    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
      required:
        - username
        - password
        - role

    RegisterResponse:
      type: object
      properties:
        message:
          type: string
          example: "User registered successfully"

    UserProfile:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: "chauchausoup"
        role:
          type: string
          example: "buyer, seller, admin"
        created_at:
          type: string
          format: date-time
          example: "2023-10-01T15:23:45Z"

    Transaction:
      type: object
      properties:
        transaction_id:
          type: integer
        buyer_id:
          type: integer
        seller_id:
          type: integer
        amount:
          type: number
          format: float
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CreateEscrowRequest:
      type: object
      properties:
        buyer_id:
          type: string
          description: "ID of the buyer"
        seller_id:
          type: string
          description: "ID of the seller"
        amount:
          type: number
          format: float
          description: "Amount for the escrow"
        description:
          type: string
          description: "Description of the escrow transaction"
      required:
        - buyer_id
        - seller_id
        - amount
        - description

    CreateEscrowResponse:
      type: object
      properties:
        escrow_id:
          type: string
          description: "The ID of the newly created escrow transaction"
        status:
          type: string
          description: "The current status of the escrow"
        created_at:
          type: string
          format: date-time
          description: "The creation time of the escrow"

    PendingEscrowResponse:
      type: object
      properties:
        escrow_id:
          type: string
          description: "The ID of the escrow transaction"
        buyer_id:
          type: string
          description: "The ID of the buyer"
        seller_id:
          type: string
          description: "The ID of the seller"
        amount:
          type: number
          description: "The amount of the escrow transaction"
        status:
          type: string
          description: "The current status of the escrow"
        created_at:
          type: string
          format: date-time
          description: "The creation time of the escrow"
        description:
          type: string
          description: "Description of the escrow transaction"

    DisputedEscrowResponse:
      type: object
      properties:
        escrow_id:
          type: string
          description: "The ID of the disputed escrow transaction"
        buyer_id:
          type: string
          description: "The ID of the buyer"
        seller_id:
          type: string
          description: "The ID of the seller"
        amount:
          type: number
          description: "The amount of the escrow transaction"
        status:
          type: string
          description: "The current status of the escrow, which is 'disputed'"
        created_at:
          type: string
          format: date-time
          description: "The creation time of the escrow"
        description:
          type: string
          description: "Description of the escrow transaction"

    ReleaseFundsResponse:
      type: object
      properties:
        message:
          type: string
          example: "Funds released successfully"
        escrow_id:
          type: string
          description: "The ID of the escrow that was released"
        status:
          type: string
          example: "released"
          description: "The new status of the escrow after releasing the funds"
        released_at:
          type: string
          format: date-time
          description: "The timestamp of when the funds were released"

    DisputeEscrowResponse:
      type: object
      properties:
        message:
          type: string
          example: "Dispute filed successfully"
        escrow_id:
          type: string
          description: "The ID of the escrow that was disputed"
        status:
          type: string
          example: "disputed"
          description: "The new status of the escrow after the dispute"
        disputed_at:
          type: string
          format: date-time
          description: "The timestamp of when the dispute was filed"
          
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Invalid escrow ID or escrow not in pending state"

    UploadRequest:
      type: object
      properties:
        file:
          type: string
          format: binary

    CreateCustomerRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
      required:
        - name
        - email
        - phone
