name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    # Run tests with coverage and generate the coverage.out
    - name: Run tests with coverage
      run: go test ./... -coverprofile=coverage.out

    # Calculate coverage percentage and store it in a JSON file
    - name: Generate coverage badge
      run: |
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        cat <<EOF > badge.json
        {
          "schemaVersion": 1,
          "label": "coverage",
          "message": "$COVERAGE%",
          "color": "brightgreen"
        }
        EOF

    - name: Commit badge
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add badge.json
        git commit -m "Update coverage badge"
        git push
